const app=document.getElementById('app'), nav=document.getElementById('bottomNav');
const cars=[
{name:'BMW 3 серии',price:'2 450 000 ₽',meta:'2019 · 78 000 км · Москва',icon:'🚘'},
{name:'Mercedes-Benz GLC',price:'3 290 000 ₽',meta:'2021 · 56 000 км · Москва',icon:'🚙'},
{name:'Audi Q5',price:'3 150 000 ₽',meta:'2019 · 92 000 км · Москва',icon:'🚗'},
{name:'Toyota RAV4',price:'2 780 000 ₽',meta:'2020 · 68 000 км · Москва',icon:'🚕'},
{name:'Volkswagen Tiguan',price:'2 190 000 ₽',meta:'2018 · 105 000 км · Москва',icon:'🚐'}
];
const cats=[['🚘','Легковые'],['🚙','Внедорожники'],['🚗','Кроссоверы'],['🚐','Минивэны'],['🚚','Коммерческие'],['⚡','Электромобили'],['🏍️','Мотоциклы'],['🚜','Спецтехника']];
let state={screen:'home',favorite:false};
function carCard(c,i){return '<article class="car-card" data-car="'+i+'"><div class="car-pic"><button class="heart" data-fav="'+i+'">'+(state.favorite?'♥':'♡')+'</button><span class="car">'+c.icon+'</span></div><div class="car-info"><strong>'+c.name+'</strong><div class="price">'+c.price+'</div><div class="meta">'+c.meta+'</div></div></article>'}
function row(c,i){return '<article class="row-card" data-car="'+i+'"><div class="thumb">'+c.icon+'</div><div class="row-main"><strong>'+c.name+'</strong><div class="price">'+c.price+'</div><div class="meta">'+c.meta+'</div></div><button class="heart" data-fav="'+i+'">♡</button></article>'}
function header(title,back=true){return '<div class="top">'+(back?'<button class="back" data-screen="home">‹</button>':'<div></div>')+'<h1 class="title" style="margin:0;font-size:19px">'+title+'</h1><button class="icon-btn" data-action="notify">♧</button></div>'}
function renderHome(){return '<section class="screen"><div class="top"><div><div class="brand">Sell<i>Car</i></div><div class="city">⌖ Москва</div></div><button class="icon-btn">♧</button></div><input class="search" id="homeSearch" placeholder="Поиск по марке, модели или городу"><div class="grid4">'+cats.slice(0,4).map((c)=><button class="cat" data-screen="categories"><div class="cat-icon">'+c[0]+'</div>'+c[1]+'</button>).join('')+'</div><div class="banner"><strong>Проверенные автомобили</strong><span>С гарантией и юридической чистотой</span></div><div class="section-head"><h2>Популярные предложения</h2><button class="link" data-screen="search">Смотреть все</button></div><div class="cards">'+cars.slice(0,4).map(carCard).join('')+'</div></section>'}
function renderCategories(){return '<section class="screen">'+header('Категории')+'<input class="search" placeholder="Поиск по категориям">'+ '<div class="list" style="margin-top:14px">'+cats.map(c=>'<button class="row-card" data-screen="search" style="border:0;text-align:left"><div class="cat-icon" style="width:44px;flex:none;margin:0">'+c[0]+'</div><div class="row-main"><strong>'+c[1]+'</strong><div class="meta">32 548 объявлений</div></div><span>›</span></button>').join('')+'</div></section>'}
function renderSearch(){return '<section class="screen">'+header('Поиск')+'<input class="search" value="BMW" id="searchInput"><div class="segmented"><button class="on">Все</button><button>С пробегом</button><button>Новые</button></div><div class="list">'+cars.map(row).join('')+'</div></section>'}
function renderDetail(i=0){const c=cars[i]||cars[0];return '<section class="screen" style="padding-top:0"><div class="top" style="padding-top:18px"><button class="back" data-screen="home">‹</button><span></span><button class="icon-btn" data-action="favorite">♡</button></div><div class="detail-hero"><span class="car">'+c.icon+'</span><div class="dots"><i class="dot on"></i><i class="dot"></i><i class="dot"></i></div></div><div class="detail"><h1>'+c.name+'</h1><div class="big-price">'+c.price+'</div><div class="specs"><div class="spec">📅<b>2019</b></div><div class="spec">🛣️<b>78 000 км</b></div><div class="spec">⚙️<b>Автомат</b></div><div class="spec">⛽<b>Бензин</b></div></div><div class="actions"><button class="primary" data-action="message">Написать продавцу</button><button class="outline" data-action="call">Позвонить</button></div><div class="seller"><div class="avatar">👨</div><div><strong>Алексей П.</strong><div class="tiny">Частное лицо · На сайте 2 года</div><div class="stars">★ 4.8 (56 отзывов)</div></div></div><h3 style="font-size:14px">Описание</h3><p class="tiny" style="line-height:1.5">Автомобиль в отличном состоянии. Обслуживался у официального дилера. Полный комплект ключей и документов.</p></div></section>'}
function renderFavorites(){return '<section class="screen">'+header('Избранное')+'<div class="segmented"><button class="on">Автомобили</button><button>Продавцы</button></div><div class="list">'+cars.slice(0,4).map(row).join('')+'</div></section>'}
function renderChats(){return '<section class="screen">'+header('Сообщения')+'<div>'+['Алексей П.','Мария К.','Игорь С.','Дмитрий Л.','Елена В.'].map((n,i)=>'<div class="chat"><div class="avatar">'+['👨','👩','👨','👨','👩'][i]+'</div><div class="chat-main"><strong>'+n+'</strong><p>'+cars[i%cars.length].name+' · '+cars[i%cars.length].price+'<br>Здравствуйте! Актуально?</p></div><span class="time">'+(i?'вчера':'14:32')+'</span></div>').join('')+'</div></section>'}
function renderCreate(){return '<section class="screen">'+header('Новое объявление')+'<div class="form"><div class="photo-upload"><div><b>⌑</b>Добавьте фото<br><span>до 10 изображений</span></div></div><div class="field"><label>Марка и модель</label><input placeholder="Например: BMW 3 серии"></div><div class="field"><label>Год выпуска</label><select><option>Выберите год</option><option>2024</option><option>2023</option><option>2022</option><option>2021</option></select></div><div class="field"><label>Пробег, км</label><input placeholder="Например: 80 000"></div><div class="field"><label>Цена, ₽</label><input placeholder="Укажите цену"></div><button class="primary" data-action="publish">Далее</button></div></section>'}
function renderFilters(){return '<section class="screen">'+header('Фильтры')+'<div class="filters"><div class="field"><label>Марка</label><select><option>Все марки</option><option>BMW</option><option>Mercedes-Benz</option><option>Audi</option></select></div><div class="field"><label>Модель</label><select><option>Любая модель</option></select></div><div class="field"><label>Цена</label><div class="range"><input placeholder="от 500 000"><input placeholder="до 5 000 000"></div></div><div class="field"><label>Год выпуска</label><div class="range"><select><option>от 2015</option></select><select><option>до 2024</option></select></div></div><div class="field"><label>Пробег, км</label><div class="range"><input placeholder="от"><input placeholder="до"></div></div><button class="primary" data-screen="search">Показать 1 248 объявлений</button></div></section>'}
function renderProfile(){return '<section class="screen"><div class="top"><div></div><button class="icon-btn">⚙</button></div><div class="profile-head"><div class="profile-avatar">👨</div><h1>Иван Петров</h1><div class="tiny">Пользователь с 2022 года</div><div class="stars">★ 4.8 (124 отзыва)</div><div class="stats"><div><b>12</b><span>Объявлений</span></div><div><b>56</b><span>Подписок</span></div><div><b>243</b><span>Подписчика</span></div></div></div><div class="menu"><button data-screen="favorites">Избранное <span>›</span></button><button data-screen="chats">Сообщения <span>›</span></button><button>Уведомления <span>›</span></button><button>Настройки <span>›</span></button></div></section>'}
function render(){let h='';if(state.screen==='home')h=renderHome();if(state.screen==='categories')h=renderCategories();if(state.screen==='search')h=renderSearch();if(state.screen==='detail')h=renderDetail(state.car);if(state.screen==='favorites')h=renderFavorites();if(state.screen==='chats')h=renderChats();if(state.screen==='create')h=renderCreate();if(state.screen==='filters')h=renderFilters();if(state.screen==='profile')h=renderProfile();app.innerHTML=h;renderNav()}
function renderNav(){const items=[['home','⌂','Главная'],['favorites','♡','Избранное'],['create','＋','Разместить'],['chats','◌','Сообщения'],['profile','♙','Профиль']];nav.innerHTML=items.map(([s,ic,t])=>'<button class="nav-item '+(state.screen===s?'active':'')+(s==='create'?' add':'')+'" data-screen="'+s+'">'+(s==='create'?'<span>'+ic+'</span>':'<span>'+ic+'</span>')+'<small>'+t+'</small></button>').join('')}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const s=e.target.closest('[data-screen]');if(s){state.screen=s.dataset.screen;render();return}const card=e.target.closest('[data-car]');if(card){state.car=+card.dataset.car;state.screen='detail';render();return}const fav=e.target.closest('[data-fav]');if(fav){state.favorite=!state.favorite;toast(state.favorite?'Добавлено в избранное':'Удалено из избранного');render();return}const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='favorite'){state.favorite=!state.favorite;toast(state.favorite?'Добавлено в избранное':'Удалено из избранного')}if(act==='message'){state.screen='chats'}if(act==='call')toast('Демо: звонок продавцу');if(act==='publish')toast('Объявление сохранено как черновик');if(act==='notify')toast('Новых уведомлений нет');render()}})
render();